# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQI_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aqi_data',
            fields=[
                ('aqi_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(db_index=True, max_length=40)),
                ('pm25', models.CharField(max_length=8)),
                ('pm10', models.CharField(max_length=8)),
                ('o3', models.CharField(max_length=8)),
                ('so2', models.CharField(max_length=8)),
                ('no2', models.CharField(max_length=8)),
                ('co', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'aqi_data',
            },
        ),
        migrations.CreateModel(
            name='City_info',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=40)),
                ('aqi', models.CharField(max_length=8)),
                ('max_poll', models.CharField(max_length=20)),
                ('level_index', models.CharField(max_length=16)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'city_info',
            },
        ),
        migrations.CreateModel(
            name='City_local',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=40)),
                ('city_located', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'city_position',
            },
        ),
        migrations.CreateModel(
            name='data_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=40)),
                ('aqi', models.CharField(max_length=8)),
                ('max_poll', models.CharField(max_length=20)),
                ('level_index', models.CharField(max_length=16)),
                ('pm25', models.CharField(max_length=8)),
                ('pm10', models.CharField(max_length=8)),
                ('o3', models.CharField(max_length=8)),
                ('so2', models.CharField(max_length=8)),
                ('no2', models.CharField(max_length=8)),
                ('co', models.CharField(max_length=8)),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'data_history',
            },
        ),

    ]
