# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-17 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AQI_App', '0005_auto_20200317_1431'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='city_info',
            options={'ordering': ['aqi']},
        ),
    ]
