# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-18 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQI_App', '0006_auto_20200318_0013'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='city_info',
            options={},
        ),
        migrations.AlterField(
            model_name='city_info',
            name='aqi',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
