# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQI_App', '0008_auto_20200318_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_geocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('city_geocode', models.IntegerField()),
            ],
            options={
                'db_table': 'city_geo',
            },
        ),
        migrations.AlterField(
            model_name='aqi_data',
            name='pm10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='aqi_data',
            name='pm25',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data_history',
            name='pm10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data_history',
            name='pm25',
            field=models.IntegerField(null=True),
        ),
    ]
